### ISSUE TITLE
Connection via SSH

### ISSUE THREAD

**Issue by k1ll1n** [iAmGio/chorus#11]
Hi! 
Is it possible to connect to the server via ssh?

**Comment by iAmGio** [comment]
Hi. No, Chorus is just a file editor, it has nothing to do with a SSH client.

**Comment by MrLightningBlaze** [comment]
This does support FTP, and I belive that it was being asked specifically for sshfs or similar support, not a ssh client for running commands (Just want to make sure this is clear, as it seems you are thinking of this being asked about as a command ssh client, when it is about SSH based file access)
I do agree this feature would be nice, as I already have SSH setup on my local MC server, and it would be a lot easier to setup remote file access over ssh than to set up a FTP server.
