### ISSUE TITLE
Suggestion - Submit chorus to the AUR

### ISSUE THREAD

**Issue by alsoGAMER** [iAmGio/chorus#15]
Submit chorus to the AUR so the user can install it using the package manager and it will also install all of the dependencies needed by chorus to run

https://wiki.archlinux.org/index.php/Arch_package_guidelines_(Italiano)#Invio_di_pacchetti_ad_AUR

**Comment by iAmGio** [comment]
I don't really see the point of this. Chorus doesn't need any installation and contains required dependencies by default.
