### ISSUE TITLE
SCP / SSH Support

### ISSUE THREAD

**Issue by Nachtalb** [iAmGio/chorus#17]
I haven't used the app yet but it looks awesome! Because I do not have nor want to setup FTP/SFTP set up on my server I ask you if you could add SCP support. The neat thing of course with SCP is that simply works without any additional setup on a server. I think many could profit from it.

**Comment by iAmGio** [comment]
Hi @Nachtalb, although I'm not very familiar with SCP, I've read that Jsch - the library Chorus uses for SFTP - supports this protocol too. Please try it out and let me know!

**Comment by Nachtalb** [comment]
SCP works with the SSH protocol and for that, you can either have a setup where you have to enter a password or you can authorize with your SSH key (https://www.ssh.com/ssh/public-key-authentication). 
My setup works with key authentication and the user does not have a password set (on Linux passwords are optional). Thus I can't use it as is atm.

**Comment by iAmGio** [comment]
Chorus already supports key authentication, just check the instructions given under the text area in SFTP settings. I'll improve this system in the future though.

**Comment by Nachtalb** [comment]
Oh damn I'm sorry I'll try that then
