### ISSUE TITLE
Provide building instructions in README.md

### ISSUE THREAD

**Issue by josephworks** [iAmGio/chorus#19]

**Comment by josephworks** [comment]
bump

**Comment by josephworks** [comment]
Whatever, I am just going to have to create my own build system and fix all of the issues.

**Comment by jwpjr-dev** [comment]
+1

**Comment by iAmGio** [comment]
Hi and sorry for the delay. I think the README already says it all, just download the JAR/EXE and run it.

**Comment by josephworks** [comment]
Do you really call that build instructions... That's how I run the final
project, how would I compile from source. Compiling from source, THATS
build instructions.

**Comment by iAmGio** [comment]
I've finally converted Chorus to a Maven project (yes, I had no clue how to use it back in the days...). Now you should be able to build the software easily. Let me know if any error occurs.

**Comment by josephworks** [comment]
Ok, I will! Thanks!

**Comment by jwpjr-dev** [comment]
Seems legit. Thank you very much!
