### ISSUE TITLE
Suggestion - GUI detection

### ISSUE THREAD

**Issue by VerumUK** [iAmGio/chorus#2]
Support for plugins like DeluxeMenu's and other GUI based plugins would be nice where we highlight a section of the config, right click and GUI preview it will read the data and add in the items to the preview so we can see how it will look, rather than having to manually enter it all each time we want to make changes.

**Comment by iAmGio** [comment]
Hi,
since there is no plugin-specific support in the software yet, I'm not going to implement this at the moment. However, I think I'll have to contact the developer of each plugin.
