### ISSUE TITLE
Complete Build Failure

### ISSUE THREAD

**Issue by josephworks** [iAmGio/chorus#21]
Have you tried downloading the source and compiling it?
It doesn't build at all, I've tried multiple fixes through maven and intellij.

**Comment by josephworks** [comment]
I did more digging, and Chorus only works on Oracle Java (I use (Adopt)OpenJDK).

I recommend that chorus is updated to java 11 (cause it uses JavaFX), and bundle java 11 with chorus.

Here: https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8

**Comment by iAmGio** [comment]
I'm aware of this, as of now Chorus runs only on JRE/JDK < 11.
I'll gather some information about migrating and decide if it's the case to do so (retrocompatibility, jar size etc).

**Comment by jwpjr-dev** [comment]
Yeah, I had this issue as well.  I even switched to OpenJDK to try and get it to work.  Still haven't found a clear solution.
