### ISSUE TITLE
(Mac) Having a non-file tab open other than the first one hides menu bar

### ISSUE THREAD

**Issue by jwpjr-dev** [iAmGio/chorus#22]
If you open settings, it creates a mac-based tab:
![Screenshot at Dec 02 14-03-25](https://user-images.githubusercontent.com/39033698/100919465-d4d76200-34a7-11eb-921a-276cee62e279.png)
However, files work just fine:
![Screenshot at Dec 02 14-03-40](https://user-images.githubusercontent.com/39033698/100919489-dbfe7000-34a7-11eb-97d4-503f69c3d236.png)

This is abnormal behaviour and should be handled as a "custom" tab, the same as with files.  This behaviour can also be seen in Visual Studio Code:
![Screenshot at Dec 02 14-14-47](https://user-images.githubusercontent.com/39033698/100920170-bfaf0300-34a8-11eb-88a8-39a1b2bc7684.png)

**Comment by iAmGio** [comment]
I'm pretty sure this would need native code. I purposely decided not to implement native support in order to keep supporting all the platforms Java runs on. Closing this for the moment.

**Comment by jwpjr-dev** [comment]
Ah, I see.

**Comment by jwpjr-dev** [comment]
I noticed that it does not do this outside of fullscreen, it simply creates a new window.  This is just the default Mac method of creating a new window in fullscreen.
