### ISSUE TITLE
(Mac) Custom menu bar used rather than macOS menu bar

### ISSUE THREAD

**Issue by jwpjrdev** [iAmGio/chorus#23]
The macOS menu bar looks like this:
![Screenshot at Dec 02 14-19-58](https://user-images.githubusercontent.com/39033698/100920685-78754200-34a9-11eb-9611-1330f74377b9.png)
This is the ideal menu bar option for Mac.
Chorus uses this:
![Screenshot at Dec 02 14-20-28](https://user-images.githubusercontent.com/39033698/100920750-90e55c80-34a9-11eb-8b86-6f7b40094fdb.png)

I have found a potential solution to this issue, but I have not tested it: https://stackoverflow.com/questions/22569046/how-to-make-an-os-x-menubar-in-javafx

**Comment by iAmGio** [comment]
Thanks for the suggestion, that would be a nice touch for the next versions.

**Comment by iAmGio** [comment]
A native menu bar has been successfully implemented, thank you @jwpjrdev.
