### ISSUE TITLE
(Suggestion) Add support for multiple editor fonts, as with Visual Studio Code

### ISSUE THREAD

**Issue by jwpjrdev** [iAmGio/chorus#24]
I noticed that in the enumeration `org.chorusmc.chorus.editor.EditorFont` that custom editor fonts are not supported.
My suggestion is to revise the existing system to allow users to upload their own fonts.

**Comment by iAmGio** [comment]
The feature has been implemented. Now you just need to create a folder in `chorus/fonts` named after your font family (case-sensitive) containing different font weights.
