### ISSUE TITLE
Hope to provide a link that can be downloaded in mainland China

### ISSUE THREAD

**Issue by inrhor** [iAmGio/chorus#27]
This link cannot be downloaded for most users in mainland China: http://chorusmc.org

This is a great software.

**Comment by iAmGio** [comment]
Hi. you should access the website via HTTPS (https://chorusmc.org).
If that doesn't work either, download the latest version from the [releases](https://github.com/iAmGio/chorus/releases) section.

> This is a great software.

Thank you! :)
