### ISSUE TITLE
Can't add SFTP servers

### ISSUE THREAD

**Issue by KickSquareMC** [iAmGio/chorus#28]
Hello, when I try to connect to ftp, it doesn't work. Here are some images:
![image](https://user-images.githubusercontent.com/75801179/113656306-733f2400-9650-11eb-8dc5-624f9a234b7f.png)
![image](https://user-images.githubusercontent.com/75801179/113656318-7c2ff580-9650-11eb-9471-07bdd9a2a54f.png)
![image](https://user-images.githubusercontent.com/75801179/113656329-80f4a980-9650-11eb-98c9-0b671c43f177.png)
(I blurred some of the info for obvious reasons)
Am I doing something wrong or is this a bug?

**Comment by iAmGio** [comment]
Hi, make sure you're typing in the SFTP - not FTP - text area, insert `IP|Username` and check if it appears correctly. Add `|Port` if you're not using the default port. 
Click `Open from SFTP` and will be asked to insert your password.
