### ISSUE TITLE
Use jar2app to package as .app on macos. 

### ISSUE THREAD

**Issue by theMackabu** [iAmGio/chorus#31]
This software, [jar2app (github link)](https://github.com/Jorl17/jar2app) can be used to package the macos jar as an app. 
![Screen Shot 2021-04-21 at 7 29 36 PM](https://user-images.githubusercontent.com/32078755/115646976-ee9f0780-a2d7-11eb-9eb3-6040bbfd4945.png) 
It seems to work fine without issues, and can assign an app icon, and change the tab bar name.

**Comment by iAmGio** [comment]
Oh, great! I'll look forward to it.

**Comment by iAmGio** [comment]
I'm not very familiar with MacOS, should I just distribute the .app file generated from jar2app?

**Comment by theMackabu** [comment]
that is right

**Comment by theMackabu** [comment]
but you could zip it or put it in a dmg

**Comment by iAmGio** [comment]
Great, Chorus 1.3.1 will have its own Mac app, thank you for suggesting me that tool!
