### ISSUE TITLE
Multi-language Wiki parse

### ISSUE THREAD

**Issue by ahdg6** [iAmGio/chorus#32]
I have known that there is a wiki feature in released version.
But It would be better to show translated version of official wiki when user is using another language.

Example:
 English:https://minecraft.fandom.com/wiki/Minecraft_Wiki
 Chinese:https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki

**Comment by iAmGio** [comment]
Hi, Chorus currently fetches data from the official Minecraft wiki. I think that getting information out of fan-made wikis may not be the best choice. Moreover, as far as I have seen, the same page in different wikis can have different structure and/or content, thus this process could be a bit overkill to implement.
