### ISSUE TITLE
Can't go "up" (parent folder) in SFTP

### ISSUE THREAD

**Issue by Tomasan7** [iAmGio/chorus#34]
When I open a folder in SFTP there is no option to go back to the parent folder. And when I re-start the program and open SFTP again it is in the folder I left, so there is no chance to get to the root folder
![Snímek obrazovky 2021-05-15 201659](https://user-images.githubusercontent.com/47734291/118374134-c5ae2180-b5ba-11eb-9621-a9b01a1e7a7b.png)

**Comment by iAmGio** [comment]
My bad, I made the `..` button appear only when a parent folder exists, but I didn't consider the root `/` folder.

**Comment by iAmGio** [comment]
Hello, I have tried to reproduce this issue but I can't figure out how. The `..` button seems to be always displayed correctly. Could you please provide more information?

**Comment by Tomasan7** [comment]
I made a [video](https://youtu.be/-oUIGncKr88) about the bug (fresh install*). Also when you add the sftp in settings, you have to restart the program for it to take effect.

* Considering everything is saved in the folder located with the .exe

**Comment by iAmGio** [comment]
I could not properly test the fix without reproducing the issue, but it should work now. I will be releasing version 1.3.1 soon.

**Comment by Tomasan7** [comment]
It works now, thanks :)
