### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by DaNseRYT** [iAmGio/chorus#4]
![image](https://user-images.githubusercontent.com/33249522/42106723-b67386de-7bdd-11e8-97d6-ea42d7ae2cb9.png)

**Comment by iAmGio** [comment]
Are they Russian characters?

**Comment by DaNseRYT** [comment]
Yes!

**Comment by iAmGio** [comment]
I tried copying some characters from the internet, but it looks like it's working nice.
![img](https://i.imgur.com/Gp7jOJn.png)

Could you please provide these caracters as plain text?

**Comment by DaNseRYT** [comment]
mp4 - http://cdn.lumixcloud.ru/tmp/t47rgh8j9eiw.zip
yaml - http://cdn.lumixcloud.ru/tmp/2c2c.yml

**Comment by DaNseRYT** [comment]
http://www.abakbot.ru/online-5/301-rus-eng-alphabet
![image](https://user-images.githubusercontent.com/33249522/42134407-f7e4aa14-7d43-11e8-91de-a7066e418647.png)

**Comment by DaNseRYT** [comment]
Recent version. My Windows 10 PC. Server Debian 8


http://cdn.lumixcloud.ru/tmp/t47rgh8j9eiw.zip
http://cdn.lumixcloud.ru/tmp/2c2c.yml

**Comment by iAmGio** [comment]
[Fixed](https://github.com/iAmGio/chorus/commit/7320ef38c3d23557e56b2abe7a3ff6f623f640d1).
