### ISSUE TITLE
How do I import fonts? I tried importing them but it seems like it doesn't show up.

### ISSUE THREAD

**Issue by Mengyboi** [iAmGio/chorus#42]
![image](https://user-images.githubusercontent.com/85426783/169674289-d66cdd42-49fc-4e78-b736-693256dee174.png)
![image](https://user-images.githubusercontent.com/85426783/169674292-e6d828a3-0b82-4abe-877a-995fbaeb6185.png)

Maybe I'm just being dumb or something. lol

**Comment by iAmGio** [comment]
Hello @Mengy, the .otf or .ttf files must be put inside a folder named exactly like the font. To see the font name (on Windows), double click any .otf file and check the window title.
However, from experience, it looks like some fonts don't get displayed even if chosen from settings. If I remember correctly San Francisco is one of those, alongside JetBrains Mono and others, but I haven't figured out why yet.

**Comment by iAmGio** [comment]
I'm currently on macOS, but it works the same way. In my case, the window should be named _Roboto Mono_.

![Font window](https://i.imgur.com/bSzui2L.png)
