### ISSUE TITLE
Typical keybinds don't exist

### ISSUE THREAD

**Issue by ZBLL-CUBER** [iamgio/chorus#45]
I cannot undo, redo, copy, paste, select all, cut - nothing. While the keybinds for those do not exist at all in Chorus, there are buttons that claim to redo and undo in the edit tab - they sometimes work and sometimes don't. Unfortunately, I cannot comfortably use Chorus without those keybinds, and I imagine that there are other people that can't either. I suggest this to be added just like with any normal text editor.

**Comment by iamgio** [comment]
@ZBLL-CUBER these keybinds are not implemented by Chorus - it is RichTextFX, the library responsible for the whole text editor component, that handles them.  
The undo/redo actions in the edit tab actually invoke these shortcuts.

What OS are you using?

**Comment by ZBLL-CUBER** [comment]
I am using Windows 10 and it appears to work now. Cosmic ray error? xD I'll close this, if the error appears again I'll open a new one
