### ISSUE TITLE
File modified when opened

### ISSUE THREAD

**Issue by Hazae41** [iAmGio/chorus#5]
When I open a YAML file with Chorus in a JAR archive using WinRAR, it says that the YAML file has been changed, and ask me if I want to save the changed YAML file in the archive.

![](https://i.imgur.com/nNtawnW.png)

![](https://i.imgur.com/8Cn5qtt.png)

**Comment by iAmGio** [comment]
Does this happen in archives only?

**Comment by Hazae41** [comment]
It does

**Comment by lucas-luchack** [comment]
Not that, also via FileZilla!

**Comment by iAmGio** [comment]
Closing it since it isn't actually a Chorus bug.
